#!/usr/bin/env bash
set -xe

source common.sh
source build_utils.sh

BAREMETAL_RUNTIMECFG_VERSION="$1"
if [ -z "${BAREMETAL_RUNTIMECFG_VERSION}" ]; then
    echo "usage: $0 <$BAREMETAL_RUNTIMECFG_STREAM version>" >&2
    echo "example: $0 4.3.0.ipv6-2019-11-01-0001" >&2
    exit 1
fi

check_prereqs $BAREMETAL_RUNTIMECFG_STREAM || exit 1

build_image "$BAREMETAL_RUNTIMECFG_STREAM" $BAREMETAL_RUNTIMECFG_VERSION $BAREMETAL_RUNTIMECFG_STREAM \
             $BAREMETAL_RUNTIMECFG_GIT_URI $BAREMETAL_RUNTIMECFG_GIT_REF $BAREMETAL_RUNTIMECFG_DOCKERFILE
